#!/bin/sh

#+ qtivtransform 
export GST_DEBUG=4
/data/gst-pipeline-app --gst-debug-no-color  -e qtiqmmfsrc name=qmmf0 camera=0 video_1::source-index=0 ! \
"video/x-raw(memory:GBM),format=NV12,width=1920,height=1080,framerate=30/1" ! \
omxh264enc target-bitrate=32000000 control-rate=2 interval-intraframes=29 ! \
h264parse config-interval=-1 ! rtph264pay pt=96 ! udpsink host=127.0.0.1 port=8554 \
qmmf0. ! video/x-raw,format=NV12,width=1280,height=720,framerate=10/1 ! \
qtivtransform ! "video/x-raw, format=RGB, width=(int)416, height=(int)416, framerate=10/1" ! fakesink
