#!/bin/sh

export XDG_RUNTIME_DIR=/dev/socket/weston
/data/gst-pipeline-app --gst-debug-no-color -e qtiqmmfsrc camera=0 \
video_1::source-index=0 \
video_2::source-index=0 \
video_3::source-index=0 \
name=qmmf0 ! \
"video/x-raw(memory:GBM),format=NV12,width=1920,height=1080,framerate=30/1" ! qtijpegenc ! fakesink \
qmmf0. ! "video/x-raw(memory:GBM),format=NV12,width=1280,height=720,framerate=10/1" ! qtivtransform ! \
"video/x-raw(memory:GBM),format=RGB, width=(int)416, height=(int)416, framerate=10/1" ! fakesink \
qmmf0. ! "video/x-raw(memory:GBM),format=NV12,width=1920,height=1080,framerate=30/1" ! waylandsink sync=false fullscreen=true
