#!/bin/sh

# This script excuted by customized gst-pipeline-app
# $1: statusID, $2: The round of playing.

echo $* >> /data/gst-event.log
#env >> /data/gst-event.log

[ "$1" = "" ] && exit 1
if [ "$2" -eq 1 ];then
    rm -f /data/gst-event.log
fi
[ "$2" -lt 10 ] && exit 0
case $1 in
  "0")
    echo "GST_STATE_NULL"
    ;;
  "FFFF0001")
    echo "GST_STATE_READY_TO_PLAYING"
    ;;
  "FFFF0002")
    echo "GST_STATE_READY_TO_NULL"
    ;;
  "00000004")
    echo "GST_STATE_PLAYING"
    kill $(cat /data/logcat.pid)
    kill $(cat /data/dmesg.pid)
    echo "pid of $(cat /data/logcat.pid) $(cat /data/dmesg.pid)" >> /data/gst-event.log
    logcat -c
    logcat -b kernel -c
    if [ -s /data/gst.GST_STATE_PLAYING.log ];then
       [ $(stat -c%s /data/gst.GST_STATE_PLAYING.log) -gt 14 ] && mv /data/gst.GST_STATE_PLAYING.log /data/gst.GST_STATE_PLAYING-last.log
    fi
    if [ -s /data/gst.GST_STATE_PLAYING.dmesg  ];then
       [ $(stat -c%s /data/gst.GST_STATE_PLAYING.dmesg) -gt 14 ] &&  mv /data/gst.GST_STATE_PLAYING.dmesg /data/gst.GST_STATE_PLAYING-last.dmesg
    fi
    echo "$*" > /data/gst.GST_STATE_PLAYING.log
    logcat |head -n 100000 >> /data/gst.GST_STATE_PLAYING.log &
    logcat_pid=$!
    echo $logcat_pid  > /data/logcat.pid
    echo "$*" >  /data/gst.GST_STATE_PLAYING.dmesg
    logcat -b kernel -v time  |head -n 100000 >> /data/gst.GST_STATE_PLAYING.dmesg &
    dmesg_pid=$!
    echo $dmesg_pid >  /data/dmesg.pid
    echo "logcat_pid: $logcat_pid  dmesg_pid:  $dmesg_pid" >> /data/gst-event.log
    free -m >> /data/gst-event.log
    top -n 1 -m m |grep -e gst-pipeline -e logd -e qmmf >> /data/gst-event.log
    cat /sys/kernel/debug/dma_buf/bufinfo >> /data/dma/bufinfo.txt
    cat /sys/kernel/debug/dma_buf/dmaprocs >> /data/dma/dmaprocs.txt
    cat /proc/meminfo |head -n 3 >> /data/gst-event.log
    ;;
  *)
      break
   ;;
esac
#/data # cat gst-event.log
#00000001 715
#other 00000001
#FFFF0001 715
#other FFFF0001
#00000004 716
#playing
#FFFF0002 716
#other FFFF0002
#00000001 716
#other 00000001
#FFFF0001 716
#other FFFF0001

