# Based on gst-pipeline-app.c add resolution change
help:
all:
	aarch64-oe-linux-gcc --sysroot=/usr/local/oecore-x86_64/sysroots/aarch64-oe-linux gst-pipeline-app.c -lpthread -o gst-pipeline-app -lgstreamer-1.0 -lgobject-2.0 -lglib-2.0  -pthread -I/usr/local/oecore-x86_64/sysroots/aarch64-oe-linux//usr/lib/glib-2.0/include/ -I/usr/local/oecore-x86_64/sysroots/aarch64-oe-linux//usr/include/glib-2.0 -I/usr/local/oecore-x86_64/sysroots/aarch64-oe-linux/usr/include/gstreamer-1.0/

